# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:

- {name: 'Contacto', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://instagram.com/makeupp_angela'}
- {icon: 'envelope', link: 'mailto:angelaagusti97@gmail.com'}

# Customize site text
# pagination:
   next_page: '->'
   previous_page: '<-'

sharing_button_prompt: 'Compártelo en las redes:'

related_posts: 'También te puede interesar...'

post_date_prefix: 'Publicado el'
